### ISSUE TITLE
cannot import name 'ModelPatcher' from 'comfy.sd'

### ISSUE THREAD

**Issue by spacepxl** [hnmr293/ComfyUI-nodes-hnmr#6]
```
Traceback (most recent call last):
  File "C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1698, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr\__init__.py", line 2, in <module>
    from .vae import VAEDecodeBatched, VAEEncodeBatched
  File "C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr\vae.py", line 5, in <module>
    from .model.iter import try_get_iter
  File "C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr\model\iter.py", line 4, in <module>
    from comfy.sd import ModelPatcher, CLIP, VAE
ImportError: cannot import name 'ModelPatcher' from 'comfy.sd' (C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\comfy\sd.py)

Cannot import C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr module for custom nodes: cannot import name 'ModelPatcher' from 'comfy.sd' (C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\comfy\sd.py)

```

https://github.com/comfyanonymous/ComfyUI/commit/f92074b84f44af6127e8f4ed1245d6c04dc0b750

Solution: modify import statements in iter.py and sample.py

iter.py, line 4:
```
from comfy.sd import ModelPatcher, CLIP, VAE
```
->
```
from comfy.sd import CLIP, VAE
from comfy.model_patcher import ModelPatcher
```

sample.py, line 9:
```
from comfy.sd import ModelPatcher
```
->
```
from comfy.model_patcher import ModelPatcher
```

**Comment by emourdavid** [comment]
Thank you. I can solve this issue right now

**Comment by Gloynus** [comment]
It's not working.
`
### Loading: ComfyUI-Impact-Pack (V4.30.8)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3)
Package diffusers is already installed.
### Loading: ComfyUI-Manager (V1.0.1)
### ComfyUI Revision: 1699 [0cf4e869] | Released on '2023-11-17'
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr-main\__init__.py", line 3, in <module>
    from .sample import KSamplerSetting, KSamplerOverrided, KSamplerXYZ
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr-main\sample.py", line 11, in <module>
    from .model import merge2
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr-main\model\merge2.py", line 8, in <module>
    from comfy.ldm.models.diffusion.ddpm import LatentDiffusion
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\models\diffusion\ddpm.py", line 12, in <module>
    import pytorch_lightning as pl
ModuleNotFoundError: No module named 'pytorch_lightning'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr-main module for custom nodes: No module named 'pytorch_lightning'
Total VRAM 12287 MB, total RAM 32617 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Torch version: 2.1.0+cu121
[VideoHelperSuite] - INFO - ffmpeg could not be found. Using ffmpeg from imageio-ffmpeg.
DWPose: Onnxruntime with acceleration providers detected

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Styles_CSV_Loader
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_NestedNodeBuilder
   0.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff
   0.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.2 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr-main
   0.4 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.7 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LCM
   0.7 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   1.2 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   1.7 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   4.6 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
`

**Comment by emourdavid** [comment]
You use 3 commands if you uses Windows
cd D:\ComfyUI_windows_portable\ComfyUI
venv\Scripts\activate.bat
pip install pytorch_lightning

**Comment by gerroon** [comment]
I have the same issue

```
### Loading: ComfyUI-Manager (V1.5)
### ComfyUI Revision: 1710 [d66b631d] | Released on '2023-11-21'
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: c:\\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
Can't find pypng! Please install to enable 16bit image support.
[comfyui_controlnet_aux] | INFO -> Using ckpts path: \\192.168.11.109\t\DEV\AI\STABLEDIFFUSION\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
c:\\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:24: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Traceback (most recent call last):
  File "c:\\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\nodes.py", line 1784, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\comfy_vid2vid\__init__.py", line 8, in <module>
    from .sd import load_checkpoint_guess_config, load_lora_for_models
  File "c:\\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\comfy_vid2vid\sd.py", line 3, in <module>
    from comfy.sd import load_model_weights, ModelPatcher, VAE, CLIP, model_lora_keys_unet, model_lora_keys_clip
ImportError: cannot import name 'ModelPatcher' from 'comfy.sd' (c:\\omfyUI_windows_portable_nightly_pytorch\ComfyUI\comfy\sd.py)

Cannot import c:\\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\comfy_vid2vid module for custom nodes: cannot import name 'ModelPatcher' from 'comfy.sd' (c:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\comfy\sd.py)
```

**Comment by aksoyayberk** [comment]
> ```
> Traceback (most recent call last):
>   File "C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1698, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr\__init__.py", line 2, in <module>
>     from .vae import VAEDecodeBatched, VAEEncodeBatched
>   File "C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr\vae.py", line 5, in <module>
>     from .model.iter import try_get_iter
>   File "C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr\model\iter.py", line 4, in <module>
>     from comfy.sd import ModelPatcher, CLIP, VAE
> ImportError: cannot import name 'ModelPatcher' from 'comfy.sd' (C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\comfy\sd.py)
> 
> Cannot import C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr module for custom nodes: cannot import name 'ModelPatcher' from 'comfy.sd' (C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\comfy\sd.py)
> ```
> 
> [comfyanonymous/ComfyUI@f92074b](https://github.com/comfyanonymous/ComfyUI/commit/f92074b84f44af6127e8f4ed1245d6c04dc0b750)
> 
> Solution: modify import statements in iter.py and sample.py
> 
> iter.py, line 4:
> 
> ```
> from comfy.sd import ModelPatcher, CLIP, VAE
> ```
> 
> ->
> 
> ```
> from comfy.sd import CLIP, VAE
> from comfy.model_patcher import ModelPatcher
> ```
> 
> sample.py, line 9:
> 
> ```
> from comfy.sd import ModelPatcher
> ```
> 
> ->
> 
> ```
> from comfy.model_patcher import ModelPatcher
> ```

Thanks for the solution!
I wonder why this has not applied to the main branch yet..

**Comment by aksoyayberk** [comment]
> ```
> Traceback (most recent call last):
>   File "C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1698, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr\__init__.py", line 2, in <module>
>     from .vae import VAEDecodeBatched, VAEEncodeBatched
>   File "C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr\vae.py", line 5, in <module>
>     from .model.iter import try_get_iter
>   File "C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr\model\iter.py", line 4, in <module>
>     from comfy.sd import ModelPatcher, CLIP, VAE
> ImportError: cannot import name 'ModelPatcher' from 'comfy.sd' (C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\comfy\sd.py)
> 
> Cannot import C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr module for custom nodes: cannot import name 'ModelPatcher' from 'comfy.sd' (C:\Users\****\Desktop\ComfyUI_windows_portable\ComfyUI\comfy\sd.py)
> ```
> 
> [comfyanonymous/ComfyUI@f92074b](https://github.com/comfyanonymous/ComfyUI/commit/f92074b84f44af6127e8f4ed1245d6c04dc0b750)
> 
> Solution: modify import statements in iter.py and sample.py
> 
> iter.py, line 4:
> 
> ```
> from comfy.sd import ModelPatcher, CLIP, VAE
> ```
> 
> ->
> 
> ```
> from comfy.sd import CLIP, VAE
> from comfy.model_patcher import ModelPatcher
> ```
> 
> sample.py, line 9:
> 
> ```
> from comfy.sd import ModelPatcher
> ```
> 
> ->
> 
> ```
> from comfy.model_patcher import ModelPatcher
> ```

Thanks for the solution!
I wonder why this has not applied to the main branch yet?

**Comment by aksoyayberk** [comment]
Please check https://github.com/CYBERLOOM-INC/ComfyUI-nodes-hnmr as it includes some important fixes on top of this original repo.
